### PR TITLE
Leaderboard

### PR DESCRIPTION
**Pull request by minongcopper**
Leaderboard functional. DB queries still in pg-promise. @baudot and I will have to work on getting them into his pg format.

### CODE REVIEW

**Comment by NylonEric** [comment]
Can you pull in the latest development branch changes and check the tests locally?

**Comment by minongcopper** [comment]
Yes, @NylonEric, I'll check on that. Thanks!

**Comment by minongcopper** [comment]
Alright @NylonEric , it looks like we're putting all of our CSS in styles.css. I'll follow suit and I think that'll fix the error.

**Comment by minongcopper** [comment]
Well, I think that it doesn't like that I console.log an error after an axios catch. Searchbar.jsx seems to be doing the same thing though. I need to figure out how to fix this.

**Comment by NylonEric** [comment]
The tests are probably failing because the logging is happening after the return of some async function. This page describes a possible solution. Wrap your jest tests in async/await.
```
test('shows how async / await works', async () => {
  const value = await Promise.resolve(true);
  expect(value).toBe(true);
});
```

https://www.pluralsight.com/guides/test-asynchronous-code-jest

**Comment by minongcopper** [comment]
@NylonEric, I REALLY appreciate this hint. Working on it now!

**Pull request merged**
