### PR TITLE
Sample response

### PR DESCRIPTION
**Pull request by tbrinkman3**
Sample response from api for developing components

### CODE REVIEW

**Comment by NylonEric** [comment]
I am not aware of using different files with the .env suffix. Can we just put all credentials into the .env for simplicity? I haven't seen how other file names will work with containers/deployment etc.

**Review by NylonEric — CHANGES_REQUESTED** [review]
I am not aware of using different files with the .env suffix. Can we just put all credentials into the .env for simplicity? I haven't seen how other file names will work with containers/deployment etc.

**Comment by tbrinkman3** [comment]
I did not mean to commit that, sorry! I have removed it from the pull request

**Review by NylonEric — APPROVED** [review]
This looks great.

**Pull request merged**
